### ISSUE TITLE
DGN file support

### ISSUE THREAD

**Issue by haandev** [mmomtchev/node-gdal-async#4]
If i list the supported drivers, i saw DGN there. but if i use gdal.open("any_dgn_file.dgn") it seem gdal driver is missing 

i see an error Error: Error opening dataset

**Comment by mmomtchev** [comment]
@haandev, can you provide a test file?

**Comment by haandev** [comment]
@mmomtchev i sent via mail

**Comment by mmomtchev** [comment]
@haandev, this is a Microstation DGN v8 file. GDAL/OGR must be built with ODA support in order to enable these drivers. These libraries are not publicly available. You have to became a member to get access to them. 
(from <https://gdal.org/drivers/vector/oda.html#vector-oda>)

What I suggest you do is:
Obtain the proprietary libraries
Rebuild GDAL yourself, preferably the latest version (use GDAL's own `ogrinfo` to check if your version supports your file)
Rebuild node-gdal to use your own version of GDAL instead of the one bundled with the package by doing:
```
npm install gdal-async --build-from-source --shared_gdal  
```
