### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by zdila** [mmomtchev/node-gdal-async#90]
Hello,

I am getting _Segmentation fault_ when using this library with https://github.com/FreemapSlovakia/dem-iron/tree/master and `DTM Croatia 20m v1 by Sonny.tif` from https://drive.google.com/drive/folders/1U152Bg0G1au_74ppTkZ3uNBdG-bMCXgN

I am running it on Debian 12 and Node 18 with gdal-async of the latest version on npm. Also tried older versions of Node and the library.

With Node 16 and gdal-async 3.1 I am getting
```
double free or corruption (out)
Aborted
```

**Comment by mmomtchev** [comment]
I confirm the crash, it is due to the fact that you are trying to read more than 4GB of data in a single operation. `gdal-async` uses Node.js NAN, the older Node.js API, which does not accept 64 bit integers. This means that anything over 4GB will have to use a floating point buffer size which is obviously not without risks. If I am able to come up with a safe implementation, I will extend the buffer limit to `2^53 - 1`, JS max safe integer, or otherwise I will add a safety check at 4GB.
