### ISSUE TITLE
Upgrading to Lambda Node v18 Error: /lib64/libc.so.6: version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by alexcroox** [mmomtchev/node-gdal-async#99]
Previously I was using node v16 and gdal-async was in an AWS lambda layer.

I've since started using node v18 and updated my dependencies.

I'm running on a Mac M1 so I run:

`npm install gdal-async --no-save --build-from-source --shared_gdal && npm explore gdal-async -- npm run prune`

Then I download the latest `node-v108-linux-x64` from your releases page and add that to my layer:

`nodejs/node_modules/gdal-async/lib/binding/node-v108-linux-x64/`

However Lambda is now erroring on launch with:

```Error: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/nodejs/node_modules/gdal-async/lib/binding/node-v108-linux-x64/gdal.node)```

What am I missing in these steps.

Thanks!

**Comment by alexcroox** [comment]
I'm getting this after downgrading to Lambda node v16 so I think something else is going on

**Comment by mmomtchev** [comment]
Normally Node.js 18 requires glibc 2.28 which Amazon does not propose on Amazon Linux. There is Amazon Linux 2022 and now 2023 which have it.

I don't know where is your Node.js coming from - but it is definitely not an official build from Nodesource. I guess that somebody at Amazon has hacked it to build without glibc 2.28.

Normally, in this case, this build should get assigned a new unique ABI version number. The Node.js team is the one that should provide it and the Amazon team is the one that is supposed to ask for it. This will prevent `npm` from installing pre-built binaries that are not compatible.

However whatever they decide to do, your only option is to build `gdal-async` yourself - as there won't be any prebuilt binaries for this custom version.

Or, you should upgrade to Amazon Linux 2022/2023 and use an official Node.js 18 build from Nodesource.

**Comment by mmomtchev** [comment]
Using `gdal-async@3.6.2` should also be possible

**Comment by AndrazPustotnik** [comment]
Is there any information on when Amazon Linux 2023 will be supported in AWS Lambda? I'm trying to build the latest version of gdal-async (v3.9.2) as a Lambda layer, but I'm running into issues with Node.js 18 due to the glibc limitations in Amazon Linux 2. Given the upcoming deprecation of Node.js 16.x (with AWS SDK for JavaScript v3 no longer supporting Node.js 16 after January 6, 2025), it's important to ensure future compatibility.

Is there any workaround for using Node.js 18 in Amazon Linux 2 to build the latest gdal-async layer, or should we expect support for Amazon Linux 2023 in Lambda soon?

**Comment by mmomtchev** [comment]
If you rebuild the module from source on the target host, it should work on any version.

If your target is Amazon Linux 2023, it seems that it uses the official binaries from Nodesource. This means that the prebuilt binary  should work.
